"""replace category_id with category string

Revision ID: 720beb884f0e
Revises: d1de939ee4f6
Create Date: 2026-06-17 00:20:52.508705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720beb884f0e'
down_revision = 'd1de939ee4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
